export const REQUEST_WIDGETS = 'REQUEST_WIDGETS';
export const FETCH_WIDGETS = 'FETCH_WIDGETS';


export const UPDATE_CREATE_WIDGET_MODAL = 'UPDATE_CREATE_WIDGET_MODAL';

export const REQUEST_CREATE_WIDGET = 'REQUEST_CREATE_WIDGET';
export const REQUEST_ALL_WIDGET_SUCCESS = 'REQUEST_ALL_WIDGET_SUCCESS';
export const CREATE_WIDGET_SUCCESS = 'CREATE_WIDGET_SUCCESS';

export const SEARCH_WIDGET='SEARCH_WIDGET';

export const UPDATE_LOADER = 'UPDATE_LOADER';
export const USER_LOGOUT = 'USER_LOGOUT';

